#!/usr/bin/env node
'use strict';

/**
 * acumgr setup wizard
 * Generates config.json by prompting the user for their manager address
 * and discovering processor addresses from the Acurast Mainnet chain.
 */

const readline = require('readline');
const fs       = require('fs');
const path     = require('path');

const CONFIG_PATH = path.join(__dirname, 'config.json');

const rl = readline.createInterface({ input: process.stdin, output: process.stdout });
const ask = (q) => new Promise(r => rl.question(q, r));

async function main() {
  console.log('\n╔════════════════════════════════════════╗');
  console.log('║      acumgr — Setup Wizard             ║');
  console.log('║  Acurast Processor Fleet Manager       ║');
  console.log('╚════════════════════════════════════════╝\n');

  let existing = {};
  if (fs.existsSync(CONFIG_PATH)) {
    try { existing = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8')); }
    catch(_) {}
    console.log('Found existing config. Press Enter to keep current values.\n');
  }

  // Manager address
  const defaultAddr = existing.managerAddress || '';
  const managerAddress = (await ask(
    `Manager address (SS58)${defaultAddr ? ' [' + defaultAddr.slice(0,12) + '...]' : ''}: `
  )).trim() || defaultAddr;

  if (!managerAddress || !managerAddress.startsWith('5')) {
    console.error('\n✗ Invalid address. Must be a Substrate SS58 address starting with "5".');
    process.exit(1);
  }

  // Port
  const defaultPort = existing.port || 9001;
  const portStr = (await ask(`Port [${defaultPort}]: `)).trim();
  const port = portStr ? parseInt(portStr) : defaultPort;

  // Poll interval
  const defaultPoll = existing.pollMinutes || 30;
  const pollStr = (await ask(`Poll interval in minutes [${defaultPoll}]: `)).trim();
  const pollMinutes = pollStr ? parseInt(pollStr) : defaultPoll;

  // How many processors
  const expectedStr = (await ask('How many processor phones do you have? ')).trim();
  const expectedCount = parseInt(expectedStr) || 0;

  rl.close();

  console.log('\n⏳ Connecting to Acurast Mainnet to discover your processors...');

  let ApiPromise, WsProvider;
  try {
    ({ ApiPromise, WsProvider } = require('@polkadot/api'));
  } catch(_) {
    console.error('✗ @polkadot/api not installed. Run: npm install');
    process.exit(1);
  }

  let processors = existing.processors || [];

  try {
    const provider = new WsProvider('wss://public-rpc.mainnet.acurast.com', 2500, {}, 20_000);
    const api = await ApiPromise.create({ provider });
    await api.isReady;
    console.log('✓ Connected to Acurast Mainnet\n');

    // Get our primary manager ID
    const managerIdRaw = await api.query.acurastProcessorManager.managerCounter(managerAddress);
    const managerId = managerIdRaw.toJSON();

    if (!managerId) {
      console.warn('⚠ No manager ID found for this address on Mainnet.');
    } else {
      console.log(`✓ Manager ID: ${managerId}`);

      // Scan forward from our manager ID collecting processors
      // Stop when we've found expectedCount OR hit 3 consecutive empty IDs
      const found = [];
      let emptyStreak = 0;

      for (let offset = 0; offset <= 50 && found.length < expectedCount; offset++) {
        const id = managerId + offset;
        const keys = await api.query.acurastProcessorManager.managedProcessors.keys(id);

        if (keys.length > 0) {
          emptyStreak = 0;
          // Verify each processor's manager ID matches this ID (not someone else's)
          for (const key of keys) {
            if (found.length >= expectedCount) break;
            const addr = key.args[1].toString();
            const procMgrId = await api.query.acurastProcessorManager.processorToManagerIdIndex(addr);
            if (procMgrId.toJSON() === id) {
              found.push(addr);
            }
          }
          console.log(`  Manager ID ${id}: ${keys.length} processor(s) found`);
        } else {
          emptyStreak++;
          if (emptyStreak >= 3) break;
        }
      }

      if (found.length > 0) {
        processors = found;
        console.log(`\n✓ Found ${processors.length} of ${expectedCount} processor(s)`);
        if (processors.length < expectedCount) {
          console.log(`⚠ Only found ${processors.length}/${expectedCount} processors.`);
          console.log('  You can add the remaining addresses manually to config.json');
          console.log('  under the "processors" array.\n');
        }
      } else {
        console.warn('⚠ No processors found. Check your manager address and try again.');
      }
    }

    await api.disconnect();
  } catch(err) {
    console.warn('\n⚠ Could not connect to chain:', err.message);
    console.warn('  Using existing processor list.\n');
  }

  const config = {
    managerAddress,
    port,
    pollMinutes,
    processors,
    rpc: 'wss://public-rpc.mainnet.acurast.com',
    computePallet: '5EYCAe5g86uWAqpCzj2AMUzgybxYTycRNNxSBK17aziwTZAH',
    epochLength: 900,
    _note: 'Generated by acumgr setup. Edit processors[] manually if needed.',
  };

  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2));

  console.log('✓ Config saved to config.json');
  console.log(`\n  Manager : ${managerAddress}`);
  console.log(`  Port    : ${port}`);
  console.log(`  Poll    : every ${pollMinutes} minutes`);
  console.log(`  Phones  : ${processors.length} processor(s)\n`);
  console.log('Next step: docker compose up -d --build\n');
  process.exit(0);
}

main().catch(err => {
  console.error('Setup error:', err.message);
  process.exit(1);
});
